### ISSUE TITLE
QA - Uploader - Sign Up Page - After Successfully registered Page should be redirect on login page or dashboard.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#100]
QA - Uploader - Sign Up Page - After Successfully registered Page should be redirect on login page or dashboard.
Right now After Registration, Only Success message display but page not redirect and sign up form also not cleared,

![after successfully registred page should be redirect on login page or dashboard](https://user-images.githubusercontent.com/36226408/36467385-85f59a3a-1704-11e8-886a-608c91517d04.jpg)

**Comment by acharotariya** [comment]
success message should be display on the sign up page and then after page should be redirected to login age

**Comment by brgurur** [comment]
after signup re-direct to login. works good.
