### ISSUE TITLE
QA - Uploader - Sign up Page - Validation Message should be display for Email Format.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#101]
QA - Uploader - Sign up Page - Validation Message should be display for Email Format.

Go to Sign up Page.
Enter data without email format in Email Field.
fill proper data in other fields.
click on Register button.
Observe Validation message text needs to change.

![validation message should be display for email format](https://user-images.githubusercontent.com/36226408/36467482-f9457712-1704-11e8-8617-8aa50b775720.jpg)

**Comment by brgurur** [comment]
Only one error message should be display instead of two.

![system should be display only one error message for perticular event](https://user-images.githubusercontent.com/34448885/36629976-7dc1e620-1984-11e8-9285-51648d2eccd4.jpg)

**Comment by brgurur** [comment]
works good.
