### ISSUE TITLE
QA - Uploader - Product Price - Validation Status (Server Side Validation Page) - Price type field and Global Price type fields should not be allowed numeric value. 

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#105]
QA - Uploader - Product Price - Validation Status (Server Side Validation Page) - Price type field and Global Price type fields should not be allowed numeric value. 

![price type field should not be allowed numeric value](https://user-images.githubusercontent.com/36226408/36521017-7f89854c-17ba-11e8-8f02-d04fa1c52938.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
