### ISSUE TITLE
QA - Uploader - Product Price - Validation Status (Server Side Validation Page) - Price Unit Field should be allowed only numeric values.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#106]
QA - Uploader - Product Price - Validation Status (Server Side Validation Page) - Price Unit Field should be allowed only numeric values.

![price unit field should be allowed only numeric values](https://user-images.githubusercontent.com/36226408/36521108-ffec67ea-17ba-11e8-8497-837581f28872.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
