### ISSUE TITLE
QA - Uploader - Product Price - Validation Status (Server Side Validation Page) - Special Character should not be allowed in fob_zip_code field.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#107]
QA - Uploader - Product Price - Validation Status (Server Side Validation Page) - Special Character should not be allowed in fob_zip_code field.

![special character should not be allowed in fob_zip_code field](https://user-images.githubusercontent.com/36226408/36521374-89b2c248-17bc-11e8-88f6-f61cab85d76d.jpg)

**Comment by qajha** [comment]
Need to discuss with Chirag regarding this Issue

**Comment by qajha** [comment]
This Issue is closed now as of now the devloper team resolved that Issue.
