### ISSUE TITLE
QA - Uploader - Sign In Page - Forgot Password Functionality is missing on login page.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#108]
QA - Uploader - Sign In Page - Forgot Password Functionality is missing on login page.

![forgot password functionality is missing on login page](https://user-images.githubusercontent.com/36226408/36521489-01a49c0e-17bd-11e8-8eb6-a686eced05cd.jpg)

**Comment by brgurur** [comment]
Forgot Password link was fixed.
