### ISSUE TITLE
QA - Uploader - User can not be Choose Method and upload file in uploader.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#109]
QA - Uploader - User can not be Choose Method and upload file in uploader.

it gives Permission not available for action error, but i have to Import data just 10 min ago with same subscription and same user id.

![permission error occur when user select any method for data import](https://user-images.githubusercontent.com/36226408/36523104-086191d8-17c6-11e8-887e-a6be90f4b987.jpg)

**Comment by brgurur** [comment]
Works good.
