### ISSUE TITLE
QA - Uploader - User Can not be able to upload Imprint Data using CSV file.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#115]
QA - Uploader - User Can not be able to upload Imprint Data using CSV file.

![user can not be able to upload imprint data csv](https://user-images.githubusercontent.com/36226408/36577051-bfef66fe-187a-11e8-8602-b957b3dba3de.jpg)

**Comment by brgurur** [comment]
Works good. can upload csv files.
