### ISSUE TITLE
QA - Uploader - Product Shipping - System can not be highlight the cell in record first time when user upload shipping data.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#116]
QA - Uploader - Product Shipping - System can not be highlight the cell in record first time when user upload shipping data.

When User upload Shipping data and Go to Validation Page,
First time System can not be highlighted cell.

**Comment by qajha** [comment]
Still not Working Some times.

**Comment by 80010ekta** [comment]
There is a limitation in handson table. It does not scroll properly to the last few cells in the row.

**Comment by Nikunj025** [comment]
Due to Limitation, We Close this Ticket.
