### ISSUE TITLE
QA - Uploader - Joblist - Pagination is missing on joblist.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#117]
QA - Uploader - Joblist - Pagination is missing on joblist.

![pagination is missing on joblist page](https://user-images.githubusercontent.com/36226408/36580619-fe5f9e72-188e-11e8-9e2e-a9d848c1ab40.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
