### ISSUE TITLE
QA - Uploader - "ALL" option should be selected by default in Subscription Client List.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#122]
QA - Uploader - "ALL" option should be selected by default in Subscription Client List.

After Login if we are not selecting any client from client then Subscription list does not show any data.

![all - option should be selected by default in subscription client list](https://user-images.githubusercontent.com/36226408/36626269-eccac304-1955-11e8-9317-85a83f6809dc.jpg)

**Comment by brgurur** [comment]
Works good.
