### ISSUE TITLE
QA - Uploader - User Can not be able to Select Subscription.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#145]
QA - Uploader - User Can not be able to Select Subscription.

Open Uploader.
Login with nk@yopmail.com / 123456

![user can not be able to select subscription](https://user-images.githubusercontent.com/36226408/36824319-b2b2b070-1d27-11e8-9729-baf337b975f7.jpg)

![user can not be able to select subscription 1](https://user-images.githubusercontent.com/36226408/36824568-0f960d2c-1d29-11e8-9236-a980ca78a94d.jpg)

**Comment by qajha** [comment]
Done
