### ISSUE TITLE
QA - Uploader - Sequence should be same on welcome Screen as Upload page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/uploader#164]
QA - Uploader - Sequence should be same on welcome Screen as Upload page.

**Comment by qajha** [comment]
![welcome back screen uploader](https://user-images.githubusercontent.com/36195435/37191882-5d0ee456-2388-11e8-9cd4-66858c8f82ae.png)

**Comment by Nikunj025** [comment]
Done
