### ISSUE TITLE
QA-Uploader-System is delete the one file from validation screen and also not showing the Abort and Continue button

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/uploader#165]
When user import the 5 data and then go to validate screen and first steps to validate the Product information and close the browser and again comes on validate screen and validate the second data and when the process is going on at that time user close the browser and finallay comes on same screen then system is not showing one data "Imprint charges" but its showing in Welcomes back screen and also Abort and Continue button is not showing.

![file is missing](https://user-images.githubusercontent.com/36195435/37192111-98f9c94e-2389-11e8-9ab1-07cee137ebae.png)

**Comment by Nikunj025** [comment]
Done
