### ISSUE TITLE
QA-Uploader-When we edit the Transform option then list of feature is showing but bullet symbol is overlap

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/uploader#195]
-When we edit the Transform option then list of feature is showing but bullet symbol is overlapped.

![uploader transform popup](https://user-images.githubusercontent.com/36226408/38187276-7f6b5fe4-3674-11e8-95bd-206ddc22db42.jpg)

Test Scenarios
***************
1. UI Symbols Should be Properly display at right side in the Transform Popup.

**Comment by Nikunj025** [comment]
Done.
