### ISSUE TITLE
QA - Uploader - Date Format should be mm-dd-yyyy in Transform Popup.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#196]
QA - Uploader - Date Format should be mm-dd-yyyy in Transform Popup.

![date format in transform popup](https://user-images.githubusercontent.com/36226408/38187354-ccfeff36-3674-11e8-9a2b-05a25d72ddb4.jpg)

Test Scenarios
***************
1. Date Format Should be Same in Whole Module.

**Comment by Nikunj025** [comment]
Still It should be display in yyyy-mm-dd.

![date format in transform popup 1](https://user-images.githubusercontent.com/36226408/38794647-81ab9418-4173-11e8-9584-d59e0816ad60.jpg)

**Comment by 80010ekta** [comment]
It is purposely kept in yyyy-mm-dd format as this format is used during server side validation.

**Comment by Nikunj025** [comment]
Done
