### ISSUE TITLE
QA - Uploader - Copyright Text on Dashboard is not Proper.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#70]
QA - Uploader - Copyright Text on Dashboard is not Proper.

It should be display in Footer.
text should be also Change till 2018.

![copyright text on dashboard](https://user-images.githubusercontent.com/36226408/36360134-32474140-1547-11e8-90da-0abe3e286e2d.jpg)

**Comment by brgurur** [comment]
works good.
