### ISSUE TITLE
QA - Uploader - Sometimes Uploaded Record Table is overlapped on Sidebar menu.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/uploader#81]
QA - Uploader - Sometimes Uploaded Record Table is overlapped on Sidebar menu.

Also Filter Section UI is not Proper.

![sometimes uploaded record table is overlapped on sidebar menu](https://user-images.githubusercontent.com/28082572/36404143-17980fe6-160f-11e8-8471-a5bec977bd7c.jpg)

**Comment by qajha** [comment]
Done
