### ISSUE TITLE
QA - Uploader - Country Field Missing Error display whenever user has not uploaded that field in CSV file.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/uploader#83]
QA - Uploader - Country Field Missing Error display whenever user has not uploaded that field in CSV file.

Also User use the schema for Product price.

![country field missing error display whenever user has not uploaded that field in csv file](https://user-images.githubusercontent.com/28082572/36404424-98057afa-1610-11e8-803f-275744e59135.jpg)

**Comment by qajha** [comment]
Issue resolved now in QA server
