### ISSUE TITLE
QA - Uploader - User can not be able to Add New Field Mapping.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#86]
QA - Uploader - User can not be able to Add New Field Mapping.

Only Loading Image is display but Mapping not Added.

![user can not be able to add new field mapping](https://user-images.githubusercontent.com/36226408/36406494-515e704a-161d-11e8-948d-f11d80382a8d.jpg)

**Comment by brgurur** [comment]
new field mapping working.
