### ISSUE TITLE
QA - Uploader - Joblist Page - Username field is blank in Joblist Page.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#87]
QA - Uploader - Joblist Page - Username field is blank in Joblist Page.

![username field is blank in joblist page](https://user-images.githubusercontent.com/36226408/36406960-b6557b4e-1620-11e8-9bfa-30edde1d94c2.jpg)

**Comment by qajha** [comment]
Now Email id display there if User Name is not available.
