### ISSUE TITLE
QA - Uploader - Joblist - User can not be able to understand which id display in joblist table.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#88]
QA - Uploader - Joblist - User can not be able to understand which id display in joblist table.

![user can not be able to understand which id display in joblist table](https://user-images.githubusercontent.com/36226408/36407006-078e3d7a-1621-11e8-9418-efe82485f722.jpg)

**Comment by qajha** [comment]
As per user understanding tracker id with some names not id

**Comment by qajha** [comment]
Now change is done so I have closed this ticket

**Comment by qajha** [comment]
Issue is resolved now in QA server
