### ISSUE TITLE
QA - Uploader - Product Information - Only One Alert Message should be display.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#91]
QA - Uploader - Product Information - Only One Alert Message should be display.

Uploader file with Excluding CSV format.

![only one alert message should be display](https://user-images.githubusercontent.com/36226408/36413625-408e634c-1645-11e8-89da-c14d2c2a2a65.jpg)

**Comment by brgurur** [comment]
works good.
