### ISSUE TITLE
QA - Uploader - Uploader is not working after merge.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#95]
QA - Uploader - Uploader is not working after merge.

![uploader is not working after merge](https://user-images.githubusercontent.com/36226408/36460362-025698c6-16de-11e8-8be4-3b31d2e21805.jpg)
![uploader is not working after merge 1](https://user-images.githubusercontent.com/36226408/36460366-09957bca-16de-11e8-86de-d54df417d4e0.jpg)

**Comment by brgurur** [comment]
works good now.
