### ISSUE TITLE
QA - Uploader - Upload Section - Multiple click should not be allow on Proceed button.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#96]
QA - Uploader - Upload Section - Multiple click should not be allow on Proceed button.

After Selecting Method, Multiple Click should not be allowed on Proceed Button.

![multiple click should not be allow on proceed button](https://user-images.githubusercontent.com/36226408/36460632-43d7587a-16df-11e8-8ad0-8e0cfa45a985.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
