### ISSUE TITLE
QA - Uploader - Sign Up Page - Multiple Click should not be allowed on Register button.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/uploader#99]
QA - Uploader - Sign Up Page - Multiple Click should not be allowed on Register button.

Go to Register Page.
Enter Invalid Data and click on Register Button.
Observe Multiple Error Message display.

![multiple click should not be allowed on register button](https://user-images.githubusercontent.com/36226408/36467271-fe889d0e-1703-11e8-8fb2-82ac74a9785a.jpg)

**Comment by brgurur** [comment]
Field level validation triggers good.
